---
- name: Deploy application on Minikube
  hosts: localhost

  vars:
    kubeconfig: /home/gunin/.kube/config
    frontend_yaml: "kubernetes_deployment/frontend.yaml"
    backend_yaml: "kubernetes_deployment/backend.yaml"
    database_yaml: "kubernetes_deployment/db.yaml"
    db_secret_file: "kubernetes_deployment/db-secret.yaml"
    db_configmap_file: "kubernetes_deployment/db-config.yaml"
    pvc_yaml: "kubernetes_deployment/mysql-pv.yaml"
    ingress_yaml: "kubernetes_deployment/ingress.yaml"

  tasks:
    - name: Start Minikube
      command: minikube start
      ignore_errors: true

    - name: Delete Pods running older images
      shell: kubectl delete deployment backend-deployment db-deployment frontend-deployment
    
    - name: Delete services
      shell: kubectl delete services backend-service frontend-service db-service

    - name: Delete ingress
      shell: kubectl delete ingress my-ingress

    - name: Create PVC
      shell: kubectl apply -f "kubernetes_deployment/mysql-pv.yaml"

    - name: Create DB Configmap
      shell: kubectl apply -f "kubernetes_deployment/db-config.yaml"

    - name: Create DB Secret
      shell: kubectl apply -f "kubernetes_deployment/db-secret.yaml"

    - name: Create DB deployment
      shell: kubectl apply -f "kubernetes_deployment/db.yaml"

    - name: Create Backend deployment
      shell: kubectl apply -f "kubernetes_deployment/backend.yaml"

    - name: Create Frontend deployment
      shell: kubectl apply -f "kubernetes_deployment/frontend.yaml"

    - name: Create Ingress service
      shell: kubectl apply -f "kubernetes_deployment/ingress.yaml"
