apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: guninjain/jahazbooker-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9001
        env:
        - name: DB_SERVER
          value: db-service
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
                name: db-secret
                key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-db

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 9001
      targetPort: 9001    
